/**
 * TermsPage — Terms of service. Public route, no auth required.
 * @route /terms
 */
import { useLayoutEffect } from 'react';
import { Link } from 'react-router-dom';
import '../styles/login.css';

const TermsPage = () => {
  useLayoutEffect(() => {
    document.documentElement.scrollTop = 0;
    document.body.scrollTop = 0;
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  return (
    <div className="legal-page page-transition">
      <div className="login-card legal-card">
        <h1 className="login-title">Terms of Service</h1>
        <p className="legal-updated">Last updated: March 2026</p>

        <div className="legal-body">
          <p>By using BowlWise, you agree to these terms.</p>

          <h2>The Service</h2>
          <p>BowlWise provides personalized dog food recommendations based on your pet's profile. Recommendations are generated by a scoring algorithm and are not veterinary advice.</p>

          <h2>Not Veterinary Advice</h2>
          <p>This app is an informational tool, not a substitute for professional veterinary guidance. Always consult your veterinarian before making significant changes to your pet's diet, especially for pets with health conditions.</p>

          <h2>Accounts</h2>
          <ul>
            <li>You are responsible for access to your email address (used for login)</li>
            <li>One account per email address</li>
            <li>We may suspend accounts that violate these terms</li>
          </ul>

          <h2>User Data</h2>
          <ul>
            <li>You retain ownership of your data</li>
            <li>See our <Link to="/privacy" className="legal-link">Privacy Policy</Link> for how data is handled</li>
            <li>You can delete your account and data at any time</li>
          </ul>

          <h2>Product Information</h2>
          <ul>
            <li>Product data (prices, ingredients, availability) is sourced from retailers and may change</li>
            <li>We do not guarantee accuracy of third-party product information</li>
            <li>Prices shown are for reference only and may differ at point of purchase</li>
          </ul>

          <h2>Limitation of Liability</h2>
          <p>BowlWise is provided "as is". We are not liable for any decisions made based on recommendations provided by the app.</p>

          <h2>Changes</h2>
          <p>We may update these terms. Continued use of the app constitutes acceptance.</p>

          <h2>Contact</h2>
          <p>Questions: <a href="mailto:jaberi.mahyar@gmail.com" className="legal-link">jaberi.mahyar@gmail.com</a></p>
        </div>

        <div className="legal-footer">
          <Link to="/privacy" className="legal-link">Privacy Policy</Link>
          <span className="legal-dot">&middot;</span>
          <Link to="/" className="legal-link">Back to App</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
